### ISSUE TITLE
events/ideas for block #1000000

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#129]
please brainstorm ideas, like:

* who stakes block #1000000 gets a prize ?
* countdown timer at various places ?
* ...

we are currently at block #904855

**Comment by Scalextrix** [comment]
What about a meme challenge for publicity?

**Comment by jericomanapsal** [comment]
I suggest a community-funded torrential rain! :D it should last for, say 8 hours.
How about a compiled 30s-60s video from the admins and everyone who wants to say thank you or anything they want?
A presentation of what we've accomplished so far? Like the story of forks and how it was solved?
Gridcoin mascot! Or at least a small image that is hosted and can be used anywhere, somewhat part of promotion.
Making a generic Gridcoin media? Example, 10s animated introductory vid, to be used for video uploads on YouTube. The current art that's always seen on steemit is good btw.
I like the meme idea by @Scalextrix  btw.
I think I need a !coffee to think of other stuff that might be fun, I'll be right back here once I've thought of something :D

**Comment by tomasbrod** [comment]
A Hard Fork to celebrate the 1e6th block.

Time left:
(1000000 − 904965) ⋅ 90 seconds_per_block
= 98 d + 23 h + 52 min + 30 s

**Comment by Erkan-Yilmaz** [comment]
comment:
"The Foundation should consider giving away a million GRC (probably as a number of smaller prizes). It's a substantial expense, but it's a once-in-the-coin's-lifetime chance to attract some real attention and the fact that it's a substantial amount is invaluable publicity."
(see [here](https://www.reddit.com/r/gridcoin/comments/6cg3jk/gridcoin_block_100000_is_coming_ideasevents/dhur95t/))

**Comment by grctest** [comment]
@tomasbrod We will likely need to perform a couple hardforks in the future, considering the changes we're talking about with staking mechanisms/neural-network improvements/etc, so setting a date far ahead in the future is a great idea!

**Comment by RobertoGaudio** [comment]
I like the idea with the million GRC giveaway, distributed evenly between all wallets which are online at that exact moment. This would be a huge advertising chance, never underestimate the human greed. If you promote this one million giveaway on all possible channels i'm sure it would go viral and pull a hell of a lot more Gridcoin users which would significantly push BOINC computation.
Headline: The Gridcoin Foundation started a ONE MILLION GRC (approx. 67.000 US$) free giveaway!

**Comment by bryhardt** [comment]
Doing the giveaway makes easy sense, and is easy marketing, but tying it to things which have more substance is trickier. If the giveaway is the focus, then once it is over, what will be left? The million block lasts for 90 seconds, how can the million block campaign last a day or week? If the million giveaway could be tied to helping GRC get lots of attention to the general public or at least science public, maybe something more could come out of it. 

Totally brainstorming here…

For the week of the event:
	- “best fans of science week”
	- social media showing off research rigs
	-  social media for best projects
	- attention to boinc
	
For the day of the event:
	- 

For the 1,000,000 block
	- social media selfies with the grid coin client
	- rain

**Comment by Erkan-Yilmaz** [comment]
more ideas in comments [here](https://steemit.com/gridcoin/@erkan/events-ideas-for-gridcoin-s-block-1000000)

**Comment by Mercosity** [comment]
I think this is an opportunity not to be missed even from the public relations side of things.
We need at least a weeks build up to the millionth block to gain any traction at all. 
Why not get users to send in a 20 second "Congratulations to Gridcoin on the Millionth Block". 
They can wear masks, crazy disguises, do crazy things or simply says congratulations. 
Maybe we can get some famous personalities to participate.
A compilation of these 20 second videos could then be made and disseminated across the various social media and other platforms on the web. Could be a lot of fun. 
The logistical difficulties of doing something like this shouldn't put us off as the overall benefit for all of us will be far reaching.

**Comment by Erelas** [comment]
A few years ago, the wife and I started a cottage industry, Swamp Bubbles Studios.  We're happy to donate our skill and time in creating near anything in our capability to help promote GRC.  A couple of things we considered, since Erkan mentioned a mascot, as my wife is stupendously talented with projects like that.  
Since a lot of crunching for SETI is done, and Joe Public thinks "Grays" when he hears SETI, we thought a plush "Gray", complete with spray on tan, gold chain with attached GRC logo medallion, and the hair from that host on the History Channels, "Ancient Aliens", name of Georgio (sp?)  That host has such a unique look and outlook, he should trademark himself.
That's just she and I goofing around with ideas at home, and a mockup could easily be presented, but, as has been discussed in other places, "hearts are deep, but pockets are shallow" and the materials to handmake an heirloom quality plush "mascot" like that would have to be fronted.  (That pesky voting problem)
Another thought, is my personal experience with "Challenge Coins", that you see around many military communities internationally, made from base metals, and sometimes precious, with a GRC logo on one side and something about a millionth block on the other.  I had some work done before by a private mint in the US, many years ago, but I'd happily contact them, would need artwork and permission to use such, before they would let me know anything, because a business wants fiat up front.
Thirdly, and this is kind of "out there", we produce about 90 lbs of artisan soap a month, mostly sold in local markets, or special orders with imprints or casts for anniversaries, company logos, etc.  We own a mint farm that coincidentally provides us mint for that.  Crypto is "minted", Mint is, ummm, minty, and I'm sure some artistic person could provide artwork to be imprinted directly, or sculpted (my thing) to construct molds celebrating the millionth block being minted in mint fashion with mint soap....yes, I am typing stream of consciousness.

So, anyway, hi, we're here, we have time, and we're willing to lend our experience to ideas we haven't even thought of yet, just let us know.  E-mail is best, but I will check back here, though actually having an account on GitHub is new for me personally.

**Comment by Mercosity** [comment]
@Erelas, your SETI gray idea sounds hilarious.

With respect to the coin side, we are in the process of designing and mocking up a commemorative coin for the millionth block on Slack. Please join us we could do with your opinion and feed back.

Contact us on Slack:

https://teamgridcoin.slack.com

**Comment by JoeGrae** [comment]
I am against giving away 1M GRC to random user/user that have their wallets open at the time the 1m block is moned. There are much greater things that can be achieved with 1M GRC. Supporting or even founding a science project for example.

I don't have a clear conecpt of it yet. It's just a thought i wanted to share.

**Comment by Erkan-Yilmaz** [comment]
See also:

* [Stake Gridcoin's 1 million block and... get a prize!](https://steemit.com/gridcoin/@erkan/stake-gridcoin-s-1-million-block-and-get-a-prize)
* tell your story... [why do you like BOINC and Gridcoin ?](https://steemit.com/gridcoin/@erkan/1million-block-event-with-prize-tell-your-story-why-do-you-like-boinc-and-gridcoin)
* [slogan + meme contest](https://steemit.com/gridcoin/@erkan/1million-block-event-with-prize-slogan-meme-contest)
* [create Gridcoin media](https://steemit.com/gridcoin/@erkan/1million-block-event-with-prize-create-gridcoin-media-pictures-videos-songs) (pictures, videos, songs, ...)
* [create adverts](https://steemit.com/gridcoin/@erkan/create-adverts-for-the-day-or-the-week-before-the-gridcoin-s-million-block) for the day (or the week) before Gridcoin's million block
* [product ideas for Gridcoin and BOINC](https://steemit.com/gridcoin/@erkan/1million-block-event-with-prize-product-ideas-for-gridcoin-and-boinc)
* [rain large GRC amount](https://steemit.com/gridcoin/@erkan/rain-large-grc-amount-when-gridcoin-stakes-its-1-million-block) when Gridcoin stakes its 1-million-block

**Comment by Mercosity** [comment]
Time is getting short ..

**Comment by Erkan-Yilmaz** [comment]
yeah, about 6900 blocks away (which is like 7 days or so)

**Comment by MagixInTheAir** [comment]
Should we close ? Block #1M happenned > 1week ago

**Comment by Erkan-Yilmaz** [comment]
good idea :-)
* all info [here](https://steemit.com/gridcoin/@erkan/brain-food-while-you-wait-for-gridcoin-s-1-million-block)
