### ISSUE TITLE
Marketing/Business Bounty?

### ISSUE THREAD

**Issue by hovai** [Erkan-Yilmaz/Gridcoin-tasks#131]
Hi there.

Is there a bounty for developing the marketing/business side of GRC?  At this point in GRC's development, when I say marketing/business I essentially mean translating the technical aspects of GRC into more palatable language.

I have a background in writing and film production, including animation, and I work in marketing and business.  I started BOINCing with GRC a little over 3 years ago and have been following it since.  

I am volunteering to create a short term marketing, business, and development plan focusing on the unexplored potential of PoR through BOINC and GRC.  It would explain the blockchain, its problems (PoW, ASIC, farms, etc), potential solutions (PoS), and how GRC utilizes PoS in tandem with PoR.  It would then explore past issues now fixed, current issues being fixed, known issues in need of fixing, and current discussions on the future of GRC (Team restrictions etc.).

I am volunteering to create it -- GRC was my first "oh hey, look at that" blockchain, and it's to the point that such a plan is becoming necessary, however... i mean... if it's there... =).

I will need help understanding some of the more technical aspects of GRC and would be more than happy to split a bounty with a team of a few dedicated to this project.

I will work on a more detailed outline over the weekend.  

In the meantime: thoughts?

**Comment by Foggyx420** [comment]
excellent, the technical aspect is defiantly been a barrier for newer users especially those with limited to zero block chain insight.

**Comment by hovai** [comment]
yeah -- there have been more tech/crypto savvy people coming in with the price spike which is good, but they're seeing GRC because of the money first, then the idea.  it would be nice to have people coming for the idea and staying for the money.

**Comment by jericomanapsal** [comment]
I think we have to specify our goals and objectives. Given the volunteer computing of BOINC projects, we should explain what is GRC, and more importantly why. Personally, I joined boinc because I like the idea of volunteer computing at my own time. I saw Gridcoin first as one of the top teams then I searched. I found out that it's a cryptocurrency, and might be a good idea to start my journey into cryptocurrencies through BOINC because it crosses all I want, volunteer computing plus cryptocurrency. While I still don't care about its value, I belive that one day this be valued as much as Gridcoin.
I think the most important question to answer here is why, next to what. For example, we need Gridcoin because we can use it to pay our bills in volunteer computing, thereby rendering the financial expenses to zero, perhaps even earn on it. We need Gridcoin because we want to reward volunteers.
It is expected that people would start and stay because of money. But hey look at this, more people are crunching numbers to generate BTC, while we crunch BOINC projects to help them, and at the same time get rewards. While it's relatively less profitable, I can say that we definitely have better purpose so we stick with it.
I agree with @Foggyx420 I used to not know blockchain technology, took me days of reading articles to finally understand the basics. It remains a challenge for some people, but this can be solved through reading existing wikis and steemit articles.

**Comment by Foggyx420** [comment]
Ive learnt on the go and started reading the code daily and learning as I go. i've contributed myself and invested in GRC.

**Comment by hovai** [comment]
i agree, @jericomanapsal.  i think the increase in monetary value of GRC helps development as it attracts interest, but marketing should focus on exactly the principals you are describing.  

our target market, in other words, should be people wanting to volunteer and contribute to decentralized computing -- from researchers to high schools -- not people trying to make profit off the increase in value of GRC.

**Comment by hovai** [comment]
moved to https://github.com/gridcoin/Gridcoin-Research/issues/378
