### ISSUE TITLE
get additional github administration rights for bugtracker

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#41]
* so easy [pull requests](https://github.com/gridcoin/Gridcoin-Research/pulls) (typos) could be merged into the code
* more difficult PRs should still require a certain procedure:
  * tested on these OS (windows, linux, ...) ?
  * done these, agreed on, test cases ? 
  * and also test cases which are relevant for the changed code parts ?
  * unit tests were added ?
  * ...
* who should get the additional flag ?

see @denravonska 's comment [here](https://steemit.com/boinc/@cm-steem/gridcoin-community-hangout-022-21th-jan-2017-9pm-gmt-rsvp-and-suggest-topics)

assigning to @grctest

**Comment by grctest** [comment]
It should be assigned to @gridcoin because he's the only one who can change this.

**Comment by denravonska** [comment]
Just to reiterate what I said/wanted to say on the hangout.

Push privileges require a good bit of trust, especially for these kind of applications. As an alternative we could have a couple of trusted developers who can take the first code reviews. When the PRs have passed those developers Rob can have a final look and do the merge. Eventually some of those developers could have gained enough trust to get push privileges but for now it's a good middle ground.

I also agree about using a development branch for continuous development and PRs instead of pushing everything into master.

**Comment by grctest** [comment]
https://cryptocointalk.com/topic/52186-gridcoin-community-development-process-idea/#entry232500

We've created a gridcoin-community organization, where we can explore improved github workflow.

What tools should we directly integrate into the org or repos?

**Comment by grctest** [comment]
Closed because we've created the gridcoin-community repo to gain these permissions. I'll create an additional issue regarding the integration of tools.
