### ISSUE TITLE
BITTREX wants to delist GRC: January 27 ("in danger")

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#42]
more trade volume needed, 5 days left

a) could also be a _money-making scheme_ by this exchange: if they'd have _lower fees_ like other exchanges, more volume would come anyways
e.g. "in danger" doesn't sound like "it will"

b) BUT: "Gridcoin featured very prominently on its frontpage" ([forum](https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1217)), so free publicity for us :-)

" This market is **in danger** of de-listing due to low trade volume and lack of user interest. It may be removed on Friday, January 27th 2017 unless the **average daily trade volume for the last 14 days exceeds 0.5 BTC**. If you would like to keep the market listed, please encourage the development team to contact us at support@bittrex.com. If you have questions about the policy, please see https://bittrex.zendesk.com/hc/en-us/articles/202583874."

https://bittrex.com/Market/Index?MarketName=BTC-GRC

**Comment by grctest** [comment]
We've been discussing this in the announcement thread: https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1217#entry232116

Ultimately, its good that they show GRC on the front page of their exchange but we have several alternative exchanges (decentralized) if we do get delisted. Several users appear to be trading on Bittrex to maintain the minimum trading volume.

**Comment by frank0051** [comment]
Well, I'm trying to use this darn exchange but I cannot get the order book to show up for me to place an order. I now have over .1BTC trapped here and I cannot trade it for GRCs :-(

**Comment by Vortac2** [comment]
They say we should contact them if we want to keep Gridcoin listed, so I've sent them the following mail:

"Dear Ladies and Gentlemen of Bittrex,

I am writing to you on behalf of the Gridcoin team. Unfortunately, our coin is currently in danger of being de-listed on your reputable crypto-exchange, due to low trade volume. While Gridcoin community is thriving and growing at an increasing pace, the current high price of Bitcoin is suppressing the whole altcoin market and Gridcoin is affected harder than most, because of its scientific and non-profit nature. We hope that the appearance of commercialized and monetized BOINC projects is going to increase the liquidity of Gridcoin in the near future.

We are kindly asking you to consider postponing the delistment of Gridcoin. We would also like to use this opportunity to thank you for featuring Gridcoin so prominently on your front page. You can rest assured that we will continue to work hard to justify your trust in our coin."

**Comment by Vortac2** [comment]
I received a reply from Bittrex. We are off the hook (again):

"Thanks for reaching out.  I'm going to remove the flag for Gridcoin.  We provide an exception for a limited number of charity coins to not have to meet the volume requirements. "

**Comment by Erkan-Yilmaz** [comment]
thank you @Vortac2
