### ISSUE TITLE
fix the NEWBIE block

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/Gridcoin-tasks#5]
The newbie block helps that newcomers:
* get a block **faster**, 
* which is also a good **feedback** ("flashing lights"), 
* and **psychological** advantage

The newbie stake weight boost could be removed and the pos:dpor stake weight rebalanced ([huppdiwupp's proposals](https://steemit.com/gridcoin/@cm-steem/pos-dpor-stake-weight-balance))

mentioned in [hangout 1](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_07_30.MD): 0:12:10

**Comment by grctest** [comment]
IMO the newbie boost should be removed, and the pos:dpor stake weight mechanism should be fully defined and potentially rebalanced.

**Comment by Erkan-Yilmaz** [comment]
problems mentioned in hangout 2 of the newbie boost:
contributes to synchronization isses and instability in stake weights

**Comment by MagixInTheAir** [comment]
Isn't the newbie boost deleted now ? #obsolete

**Comment by tomasbrod** [comment]
All sorts of Boosts are to be disabled on block 1010001 due to security issues, including the newbie boost.
There is work in progress to return some of the block creation weight to BOINCers @MagixInTheAir, see #151 and all the proposals on the [development wiki](https://github.com/gridcoin/Gridcoin-Research/wiki).

**Comment by MagixInTheAir** [comment]
Then this thread should be closed. Thanks for the links :)
