### ISSUE TITLE
Improve the performance on single board computers (increase staking participation)

### ISSUE THREAD

**Issue by skcin** [Erkan-Yilmaz/Gridcoin-tasks#69]
If we improve the performance on single board computers like the raspberry pi maybe more users will stake 24/7. 
We could provide ready to deploy images to make it easy to get started. (similar to www.peerbox.me)
Or at least provide precompiled gridcoin wallets because compiling on these devices takes some time.

Not everyone has cheap electricity and can afford to run a x86 pc 24/7.

**Comment by grctest** [comment]
open:
https://github.com/gridcoin/Gridcoin-Research/issues/166

closed:
https://github.com/gridcoin/Gridcoin-Research/issues/153
https://github.com/gridcoin/Gridcoin-Research/issues/157

PiGrid guys should dedicate some time towards this, it's integral to the success (or basic operation) of their distributed hardware. The RAM utilization of the Gridcoin client currently exceeds some low power devices.

**Comment by denravonska** [comment]
I have an ongoing quest for reducing the RAM usage and I believe it can be taken down to the same levels as the Bitcoin wallet. By loading the Gridcoin block data on demand instead of keeping it all in memory should free up some resources. However, it would come at the cost of CPU usage according to Rob. If I manage to solve the RAM issue I'll see if the potential CPU spike can be taken down.

Though I'd want a word on @gridcoin/Gridcoin-Research#203 first to avoid unnecessary refactoring.

**Comment by denravonska** [comment]
My original plan didn't work out due to slow disk access on the Pi. However, I have done some work to reduce the requirements somewhat. Are we at an acceptable level now or do we need to decrease it further?
