### ISSUE TITLE
Integrate any required/desired tools into the gridcoin-community org

### ISSUE THREAD

**Issue by grctest** [Erkan-Yilmaz/Gridcoin-tasks#76]
https://cryptocointalk.com/topic/52186-gridcoin-community-development-process-idea/#entry232500

We've created a gridcoin-community organization, where we can explore improved github workflow.

What tools should we directly integrate into the org or individual repos? We can add them as long as they're free, any requests?

https://github.com/integrations?utf8=%E2%9C%93&query=

Originally raised:
https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/41

**Comment by denravonska** [comment]
We can consider following [gitflow](https://github.com/nvie/gitflow). It's pretty well adapted so if we start using it as well people know what to expect in terms of branching, merging and releases.

**Comment by LokiToki** [comment]
I'm totally new to github and would like to see the correct usage of the default tools. Additionally i would advise to keep it as simple as possible with a clear structure. 

Is this community org repo ready-to-use? If yes i put it in the next easy-dev-start Virtual Machine instead of the master-branch.

**Comment by grctest** [comment]
The community org repo is behind master in terms of development, you should include the official gridcoin-research repo's development branch instead.
